apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
  - ../base/postgres/pvc.yaml
  - ../base/postgres/deployment.yaml
  - ../base/postgres/service.yaml
  - ../base/qdrant/deployment.yaml
  - ../base/qdrant/service.yaml
