apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  labels:
    app: MODEL_NAME
spec:
  type: ClusterIP
  selector:
    app: MODEL_NAME
  ports:
    - name: http
      port: PORT
      targetPort: PORT
