apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-3-3-70b-config
data:
  LLAMA-70B_Hopper.yaml: |
    kv-cache-dtype: fp8
    async-scheduling: true
    no-enable-prefix-caching: true
    max-num-batched-tokens: 8192
    max-num-seqs: 8
    max-model-len: 32000
