apiVersion: v1
kind: Service
metadata:
  name: llama-3-3-70b-service
  labels:
    app: llama-3-3-70b
spec:
  type: ClusterIP
  selector:
    app: llama-3-3-70b
  ports:
    - name: http
      port: 8000
      targetPort: 8000
