apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
  - ../../base
  - ../../models

patches:
  - path: patches/litellm-dev.yaml

replicas:
  - name: litellm-proxy
    count: 1
