apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
  - ../../base
  - ../../models
  - litellm-dev-deployment.yaml
  - litellm-dev-service.yaml

patches:
  - path: patches/litellm-dev.yaml

replicas:
  - name: litellm-proxy
    count: 1
  - name: litellm-proxy-dev
    count: 1

images:
  - name: ghcr.io/aihpi/litellm
    newTag: dev-qdrant-ui
