apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
  - ../../base-infra
  - ../../models
  - litellm-dev-deployment.yaml
  - litellm-dev-service.yaml
  - litellm-dev-configmap.yaml

replicas:
  - name: litellm-proxy-dev
    count: 1

images:
  - name: ghcr.io/aihpi/litellm
    newTag: dev
