apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-proxy-dev
  labels:
    app: litellm-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm-dev
  template:
    metadata:
      labels:
        app: litellm-dev
    spec:
      nodeSelector:
        node-type: cpu
      containers:
        - name: litellm
          image: ghcr.io/aihpi/litellm:aihpi-provider
          imagePullPolicy: Always
          command: ["litellm"]
          args: ["--config", "/etc/litellm/config.yaml", "--port", "4000"]
          ports:
            - containerPort: 4000
          env:
            - name: LITELLM_ASSET_PREFIX
              value: /litellm-asset-prefix
            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-secret
                  key: LITELLM_MASTER_KEY
            - name: LITELLM_CONFIG
              value: /etc/litellm/config.yaml
            - name: STORE_MODEL_IN_DB
              value: "True"
            - name: LITELLM_LOG
              valueFrom:
                configMapKeyRef:
                  name: litellm-config-dev
                  key: LITELLM_LOG
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: litellm-secret
                  key: DATABASE_URL
            - name: LITELLM_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: litellm-secret
                  key: DATABASE_URL
            - name: UI_PATH
              valueFrom:
                configMapKeyRef:
                  name: litellm-config-dev
                  key: UI_PATH
            - name: UI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: litellm-secret
                  key: UI_USERNAME
            - name: UI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: litellm-secret
                  key: UI_PASSWORD
          volumeMounts:
            - name: litellm-config
              mountPath: /etc/litellm/config.yaml
              subPath: config.yaml
      volumes:
        - name: litellm-config
          configMap:
            name: litellm-config-dev
