apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
data:
  LITELLM_LOG: info
  UI_PATH: /ui
  config.yaml: |
    model_list:
      - model_name: llama-3b
        litellm_params:
          model: openai/llama-3b
          api_base: http://llama-3b-service:8000/v1
          api_key: dummy
      - model_name: qwen-image-edit
        litellm_params:
          model: aihpi-provider/qwen-image-edit
          api_base: http://qwen-image-edit:8000/v1
          api_key: dummy
      - model_name: octen-embedding-8b
        litellm_params:
          model: openai/octen-embedding-8b
          api_base: http://octen-embedding-8b-service:8000/v1
          api_key: dummy
          encoding_format: float
        model_info:
          metadata:
            mode: embedding
      - model_name: minilm-embedding
        litellm_params:
          model: huggingface/sentence-transformers/all-MiniLM-L6-v2
          api_base: http://minilm-embedding-service:8000/v1
          api_key: dummy
          additional_drop_params: ["encoding_format"]
        model_info:
          metadata:
            mode: embedding
