apiVersion: v1
kind: Service
metadata:
  name: dinov3-embeddings-api-service
  labels:
    app: dinov3-embeddings-api
spec:
  type: ClusterIP
  selector:
    app: dinov3-embeddings-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
