apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
  - ../../base
  - ../../models
  - ingress.yaml

patches:
  - path: patches/litellm-prod.yaml

replicas:
  - name: litellm-proxy
    count: 3
