apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-oss-120b-config
data:
  GPT-OSS_Hopper.yaml: |
    async-scheduling: true
    no-enable-prefix-caching: true
    max-cudagraph-capture-size: 2048
    max-num-batched-tokens: 2048
    stream-interval: 20
  GPT-OSS_EAGLE3_Hopper.yaml: |
    async-scheduling: true
    no-enable-prefix-caching: true
    max-cudagraph-capture-size: 2048
    max-num-batched-tokens: 2048
    stream-interval: 20
    speculative-config: '{"model":"nvidia/gpt-oss-120b-Eagle3-v2","num_speculative_tokens":3,"method":"eagle3","draft_tensor_parallel_size":1}'
