apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - litellm/configmap.yaml
  - litellm/deployment.yaml
  - litellm/service.yaml
  - qdrant/deployment.yaml
  - qdrant/service.yaml
