apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
  - granite-4-h-tiny/pvc.yaml
  - granite-4-h-tiny/deployment.yaml
  - granite-4-h-tiny/service.yaml
  - gpt-oss-120b/configmap.yaml
  - gpt-oss-120b/pvc.yaml
  - gpt-oss-120b/deployment.yaml
  - gpt-oss-120b/service.yaml
  - dinov3-embeddings-api/deployment.yaml
  - dinov3-embeddings-api/service.yaml
  - fashionpedia-api/pvc.yaml
  - fashionpedia-api/deployment.yaml
  - fashionpedia-api/service.yaml
  - minilm-embedding/deployment.yaml
  - minilm-embedding/service.yaml
  - octen-embedding-8b/deployment.yaml
  - octen-embedding-8b/service.yaml
  - qwen3-vl-embedding-8b/deployment.yaml
  - qwen3-vl-embedding-8b/service.yaml
  - qwen3-vl-32b/deployment.yaml
  - qwen3-vl-32b/service.yaml
  - ministral-3-14b/deployment.yaml
  - ministral-3-14b/service.yaml
  - qwen-image-edit/pvc.yaml
  - qwen-image-edit/deployment.yaml
  - qwen-image-edit/service.yaml
  - llama-3-3-70b/configmap.yaml
  - llama-3-3-70b/pvc.yaml
  - llama-3-3-70b/deployment.yaml
  - llama-3-3-70b/service.yaml
