apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
  - llama-3b/deployment.yaml
  - llama-3b/service.yaml
  - octen-embedding-8b/deployment.yaml
  - octen-embedding-8b/service.yaml
  - qwen-image-edit/pvc.yaml
  - qwen-image-edit/deployment.yaml
  - qwen-image-edit/service.yaml
