apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
  - llama-3b/deployment.yaml
  - llama-3b/service.yaml
  - llama-70b/deployment.yaml
  - llama-70b/service.yaml
