apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
  - granite-4-h-tiny/pvc.yaml
  - granite-4-h-tiny/deployment.yaml
  - granite-4-h-tiny/service.yaml
  - gpt-oss-120b/configmap.yaml
  - gpt-oss-120b/pvc.yaml
  - gpt-oss-120b/deployment.yaml
  - gpt-oss-120b/service.yaml
  - minilm-embedding/deployment.yaml
  - minilm-embedding/service.yaml
  - octen-embedding-8b/deployment.yaml
  - octen-embedding-8b/service.yaml
  - qwen-image-edit/pvc.yaml
  - qwen-image-edit/deployment.yaml
  - qwen-image-edit/service.yaml
